---
title: "Compare Summary Statistics of Many scRNAseq Samples"
author: "Maxwell Douglas"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    
params:
  ids: "VOA10835UT, KG1_EM, VOA10286UT_control, VOA10819UT_control, DH2_control, DH5_control, DH9_control, DH11_control, DH12_control, DH14_control, DH21_control, DH22_control, VOA10835FT, KG1_FT, DH1_control, DH25_control"
---

```{css, echo=FALSE}
    body .main-container {
      max-width: 90% !important;
      width: 90% !important;
    }

    body {
      max-width: 90% !important;
    }
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
# source the files for the functions we need 
library(here)
source(here('pipeline', 'sourceFiles', 'utilities.R'))
```

```{r include = FALSE}
ids <- strsplit(params$ids, ",")[[1]]                                                       # get our ids, split by "," SO ID must NOT CONTAIN ","
ids <- trimws(ids)                                                                          # trim whitespace 
```

```{r include = FALSE}
####
# DATA PREP and LOADING
####
# here we do a bit or renaming and preparation for what is to come. 
# find the directories where the sces are and load them
sce_raws <- lapply(as.list(ids), function(id) readRDS(here('..', 'data', 'processed', id, 'sce.rds')))
sce_qcs <- lapply(as.list(ids), function(id) readRDS(here('..', 'data', 'qc', id, 'sce_qc.rds')))

# rename the sces
names(sce_raws) <- as.list(ids)
names(sce_qcs) <- as.list(ids)

# the QC metrics are saved in sces. now extract them from sces and load them into objects 
df_raws <- lapply(sce_raws, function(sce) colData(sce)) # this one has metrics before removing low quality cells 
df_qcs <- lapply(sce_qcs, function(sce) colData(sce)) # this one has metrics after removing loq quality cells 

#rename the dfs 
names(df_raws) <- as.list(ids)
names(df_qcs) <- as.list(ids)

```

```{r include = FALSE}
#####
# VISUALIZATION FUNCTIONS
#####

# This function serves to pull useful descriptive statistics out of the qc metrics we pass in as a dataframe

makeTable <- function(metrics) {
  
  TABLE <- data.frame()
  for (i in 1:length(metrics)) {
    
    # first we must go from S4 to data frame to be able to use dplyr
    df <- as.data.frame(metrics[[i]]) %>% 
      
      # get the mean for each column we are interested in 
      summarize(total_reads = sum(sum), total_cells = length(total), sum = as.integer(mean(sum)), detected = as.integer(mean(detected)), 
                subsets_mito_sum = as.integer(mean(subsets_mito_sum)), 
                subsets_mito_percent = as.integer(mean(subsets_mito_percent))) %>% 
      mutate(id = ids[i]) %>% 
      
      # here we take advantage of the select function to reorder the columns 
      dplyr::select(id, total_cells, total_reads, sum, detected, subsets_mito_sum, subsets_mito_percent) %>% 
      
      # and here we just rename them for clarity 
      rename(mean_reads = sum, mean_detected_genes = detected, mean_mito_reads = subsets_mito_sum, mean_mito_percent = subsets_mito_percent)
    
    TABLE <- rbind(TABLE, df)
  }
  
  return(TABLE)
} # end of function 
```

```{r echo = FALSE, warning = FALSE}

# Create tables of some basic descriptive statistics pertaining to the samples

raw_sumStats <- makeTable(df_raws)
qc_sumStats <- makeTable(df_qcs)

```

```{r echo = FALSE, warning = FALSE, results = 'asis'}

#####
# PLOT
#####

# Lets create those tables now

raw_sumStats %>%
  DT::datatable(
    extensions = 'Buttons',
    caption = 'Table 1: BEFORE quality control - Summary statistics of samples',
    options = list(dom = 'Bfrtip', 
                   buttons = list("copy", "excel", "csv", "pdf")))
```


```{r echo = FALSE, warning = FALSE, results = 'asis'}
qc_sumStats %>%
  DT::datatable(
    extensions = 'Buttons',
    caption = 'Table 1: AFTER quality control - Summary statistics of samples',
    options = list(dom = 'Bfrtip', 
                   buttons = list("copy", "excel", "csv", "pdf")))
```








