---
title: "Dimensionality reduction plots "
subtitle: 'DH31'
date: '`r format(Sys.Date(), "%B %d, %Y")`'

params:
  sce_clus: 'sce_clus'
  dm: 'dm_path'

output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 4
---

```{r include = FALSE}

# source some files 
library(here)
source(here("pipeline", "sourceFiles", "utilities.R"))

```

```{r}
# change this to your sample
sample_id <- "DH31"

# load sce_clus
sce <- readRDS(here("..", "data", "clustered", "sce", sample_id, "sce_clus.rds"))

# load the dm from params 
dm <- readRDS(here("..", "data", "dim_reduction", sample_id, "dm.rds"))

# set some colors for heatmap
colors_list <- c("#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3", '#E2201C', '#1D91C0', '#6B3E9A', '#32A028', "deepskyblue", "black")

min_cluster <- as.numeric(min(as.vector(sce$cluster)))
max_cluster <- max(as.numeric(as.character(sce$cluster)))

cluster_name <- min_cluster:max_cluster
colors_list <- colors_list[1:max_cluster]

```


```{r}

# make df with the diffusion map coodinates, we will use this later to make the dm plot 
tmp <- data.frame(DC1 = eigenvectors(dm)[, 1],
                  DC2 = eigenvectors(dm)[, 2],
                  DC3 = eigenvectors(dm)[, 3],
                  Timepoint = as.factor(sce$cluster), 
                  ids = sce$id) # this will help color based on cluster 

# make the 2D plot 
dm_2d <- plot_ly(data = tmp,
        x = ~DC1, y = ~DC2,
        opacity = 1,
        color = ~Timepoint,
        type = "scatter",
        mode = "markers",
        marker = list(size = 5), 
        colors = colors_list) %>% 
  layout(legend= list(itemsizing='constant'))

# make the 3d plot 
dm_3d <- plot_ly(data = tmp,
        x = ~DC1, y = ~DC2, z = ~DC3,
        opacity = 1,
        color = ~Timepoint,
        type = "scatter3d",
        mode = "markers",
        marker = list(size = 3), 
        colors = colors_list)  %>% 
  layout(legend= list(itemsizing='constant'))

# get tsne coordinates
tsne_1 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["TSNE"]][, 1])
tsne_2 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["TSNE"]][, 2])
tsne_3 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["TSNE"]][, 3])

# get pca coordinates 
pca_1 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["PCA"]][, 1])
pca_2 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["PCA"]][, 2])
pca_3 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["PCA"]][, 3])

# get pca coordinates 
umap_1 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["UMAP"]][, 1])
umap_2 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["UMAP"]][, 2])
umap_3 <- as.numeric(sce@int_colData@listData[["reducedDims"]]@listData[["UMAP"]][, 3])

# make dfs 
df_tsne <- data.frame(tsne_1, tsne_2, tsne_3)
df_tsne$id <- as.factor(sce$id) 
df_tsne$cluster <- as.factor(sce$cluster)

df_pca <- data.frame(pca_1, pca_2, pca_3)
df_pca$id <- as.factor(sce$id) 
df_pca$cluster <- as.factor(sce$cluster)

df_umap <- data.frame(umap_1, umap_2, umap_3)
df_umap$id <- as.factor(sce$id) 
df_umap$cluster <- as.factor(sce$cluster)

```

```{r include = FALSE}

# remove grid from plot_ly
ax <- list(zeroline = FALSE, showline = TRUE, showgrid = FALSE)

# TSNE
tsne_3d <- plot_ly(data = df_tsne,
        x = ~tsne_1, y = ~tsne_2, z = ~tsne_3,
        opacity = 1,
        color = ~cluster,
        type = "scatter3d",
        mode = "markers",
        marker = list(size = 4), 
        colors = colors_list) %>% 
  layout(legend= list(itemsizing='constant'))

tsne_2d <- plot_ly(data = df_tsne,
        x = ~tsne_1, y = ~tsne_2,
        opacity = 1,
        color = ~cluster,
        type = "scatter",
        mode = "markers",
        marker = list(size = 4), 
        colors = colors_list) %>% 
  layout(legend= list(itemsizing='constant'),
         xaxis = ax, yaxis = ax)


# PCA
pca_3d <- plot_ly(data = df_pca,
        x = ~pca_1, y = ~pca_2, z = ~pca_3,
        opacity = 1,
        color = ~cluster,
        type = "scatter3d",
        mode = "markers",
        marker = list(size = 4), 
        colors = colors_list) %>% 
  layout(legend= list(itemsizing='constant'))

pca_2d <- plot_ly(data = df_pca,
        x = ~pca_1, y = ~pca_2,
        opacity = 1,
        color = ~cluster,
        type = "scatter",
        mode = "markers",
        marker = list(size = 4), 
        colors = colors_list) %>% 
  layout(legend= list(itemsizing='constant'),
         xaxis = ax, yaxis = ax)

# UMAP
umap_3d <- plot_ly(data = df_umap,
        x = ~umap_1, y = ~umap_2, z = ~umap_3,
        opacity = 1,
        color = ~cluster,
        type = "scatter3d",
        mode = "markers",
        marker = list(size = 4), 
        colors = colors_list) %>% 
  layout(legend= list(itemsizing='constant'))

umap_2d <- plot_ly(data = df_umap,
        x = ~umap_1, y = ~umap_2,
        opacity = 1,
        color = ~cluster,
        type = "scatter",
        mode = "markers",
        marker = list(size = 4), 
        colors = colors_list) %>% 
  layout(legend= list(itemsizing='constant'),
         xaxis = ax, yaxis = ax)

```

# Dimension Reduction Plots 

### PCA
```{r}

pca_2d
pca_3d

```

### t-SNE
```{r}

tsne_2d
tsne_3d

```

### UMAP
```{r}

umap_2d
umap_3d

```

### Diffusion map

```{r}
dm_2d
dm_3d
```


### UMAP showing logcounts of reporter genes

```{r}
# add genes of interest here:
reporters <- c("eGFP", "dsRED", "tdTomato")

p2 <- p3 <-  htmltools::tagList()

for(i in 1:length(reporters)){
  if(any(grepl(reporters[[i]], rownames(sce), ignore.case = TRUE) == TRUE)){
    
    # if our sample contains one of the reporter genes:
    count <- logcounts(sce)
    reporter_idx <- grep(reporters[[i]], rownames(sce), ignore.case = TRUE)
    count_reporter <- count[reporter_idx,]
    df_umap$logcounts <- count_reporter
    
  p2[[i]] <- plot_ly(data = df_umap,
        x = ~umap_1, y = ~umap_2,
        opacity = 1,
        color = ~logcounts,
        type = "scatter",
        mode = "markers",
        marker = list(size = 4), 
        colors = brewer.pal(6, "Reds")) %>% 
          layout(title=paste0(reporters[[i]], "_logcount"),
         xaxis = ax, yaxis = ax)
  
    p3[[i]] <- plot_ly(data = df_umap,
        x = ~umap_1, y = ~umap_2, z = ~umap_3,
        opacity = 1,
        color = ~logcounts,
        type = "scatter3d",
        mode = "markers",
        marker = list(size = 4), 
        colors = brewer.pal(6, "Reds")) %>% 
          layout(title=paste0(reporters[[i]], "_logcount"),
         xaxis = ax, yaxis = ax)
  }
}

p2
p3

```


# Top 20 differentially expressed genes 

```{r}

# get up and down regulated genes for each cluster
markers.sce.up <- findMarkers(sce, sce$cluster, direction="up")

# a function that returns a table of top sig.genes
sig_gene_table <- function(gene_list, top=20){
  
  df <- list()
  clus_names <- numeric()

  for(i in 1:length(gene_list)){
    temp <- list(head(rownames(gene_list[[i]]), top))
    df <- append(df, temp)
    clus_names[i] <- paste("cluster", i, sep=" ")
  }

  df <- as.data.frame(df, stringsAsFactors=FALSE)
  colnames(df) <- clus_names
  return(df)
}

sig_gene_table(markers.sce.up)  %>%
  DT::datatable(
    extensions = 'Buttons', 
    options = list(dom = 'Bfrtip', 
                   buttons = list("copy", "excel", "csv", "pdf")),
    caption = "Top 20 up-regulated genes in each cluster")

```

```{r, eval=FALSE}

# a spread sheet of the significant gene table for each cluster
df <- data.frame(matrix(NA, nrow=20000, ncol=length(markers.sce.up)))
clus_names <- numeric()

for(i in 1:length(markers.sce.up)){
  sig.subset <- markers.sce.up[[i]][markers.sce.up[[i]]$p.value < 0.05,]
  temp <- rownames(sig.subset)
  diff <- 20000 - length(temp)
  df[,i] <- c(temp, rep(NA, diff))
  clus_names[i] <- paste("cluster", i, sep=" ")
}

colnames(df) <- clus_names
write.csv(df, quote=FALSE, file=paste0("/huntsman/harpcheng/", sample_id, "_sig_genes.csv"), na="")

```


# Heatmap with signature genes

A heatmap showing top 10 upregulated genes.

```{r fig.height = 15, fig.width = 16}

make_heatmap <- function(sce, all_markers){

###################### Subset count matrix ########################
# subset the sce to the markers 
idx <- na.omit(match(unlist(all_markers), rownames(sce)))
sce_subsetted <- sce[idx, ]

# accoding to type of object we are dealing with, extract the counts matrix in a different way 
if (is.null(sce$orig.ident)) {
  # if sample is an sce object
  df_main <- as.data.frame(logcounts(sce_subsetted))
} else {
  # if sample is a seurat object
  df_main <- as.data.frame(GetAssayData(object = sce[["integrated"]], slot = "data")) }

# reorder CELLS according to the clustering order in col annot
idx_main <- match(rownames(col_annot), colnames(df_main))
df_main <- df_main[, idx_main]


###################### Annotation colors ########################
# recompute min and max values
min_cluster <- as.numeric(min(as.vector(sce$cluster)))
max_cluster <- max(as.numeric(as.character(sce$cluster)))

# set column/cluster colors
cluster_name <- min_cluster:max_cluster
cluster_color_list <- c("#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3", '#E2201C', '#1D91C0', "#E7298A", '#32A028')
cluster_colors <- cluster_color_list[1:max_cluster]
names(cluster_colors) <- cluster_name

# set row/marker colors
marker_name <- paste0(names(all_markers), " markers")
marker_color_list <- c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", '#32A028', "#A0881D", "#705F48", "#595959")
marker_colors <- marker_color_list[1:length(all_markers)]
names(marker_colors) <- marker_name

# set sample colors
sample_id <- as.vector(as.character(unique(sce$id)))
sample_colors <- colorRampPalette(brewer.pal(8, "RdYlBu"))(length(sample_id))
names(sample_colors) <- sample_id

# put the above color information into a list
my_colours <- list(cluster_colors, marker_colors, sample_colors)
names(my_colours) <- c(colnames(col_annot), "marker_type", " ")


###################### make COL annotations  ###################### 
# make a data frame with colnames of the sce object as rownames here 
col_annot <- data.frame(colnames(sce), sce$cluster, sce$id, row.names = colnames(sce))
names(col_annot) <- c("column_names", "cluster", "sample_id")

# this will help order cells according to the cluster they belong to
col_annot <- col_annot[order(col_annot$cluster), ] 
col_annot$column_names <- NULL
col_annot$cluster <- as.vector(as.character(col_annot$cluster))
col_annot$sample_id <- as.vector(as.character(col_annot$sample_id))

###################### make ROW annotations ###################### 
all_names_rep <- rep(marker_name, each=10)
row_annot <- data.frame(unlist(genes), all_names_rep, stringsAsFactors = FALSE) %>% na.omit()
names(row_annot) <- c("marker_genes", "marker_type")
rownames(row_annot) <- rownames(df_main)
row_annot$marker_genes <- NULL


###################### Plot heatmap ###################### 
pheatmap(df_main,
      color = inferno(10),
      show_colnames = FALSE,
      show_rownames = TRUE,
      cluster_cols = FALSE,
      cluster_rows = FALSE, 
      annotation_col = col_annot,
      annotation_row = row_annot,
      annotation_colors = my_colours)
}


# get top 10 DEGs for clusters: modify marker list if needed
genes <- cbind.data.frame(sig_gene_table(markers.sce.up, top=10), 
                          #c(),
                          stringsAsFactors = FALSE)

print(make_heatmap(sce, genes))
```



















