---
title: "README"
author: "asli"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

#### README  
Scripts in this folder concern these samples, they are all primary tumors:  

**Ovarian samples are:**  
VOA11068_ENOC  
DH13  
DH18  
DH8  
DH24  
VOA11229_CCOC  
DH7  

**Endometrial samples are:**  
DH3  
DH4  
DH10  
DH15  
DH16  
DH17  

Using these samples, we do various types of analyses, mostly gene enrichment and DGE analysis.  
For more information on these samples, check this link:  

https://docs.google.com/spreadsheets/d/1vV94vXIDvbC1feEk7iDFtALr0M7pbCRuoBlVnkRhRgM/edit#gid=0  


#### Some background on these tumors / ideas for future analyses:   
**1.** pick one cancer type and compare ovary and endometrium for that type  
We have three cancer types we can work with:  
- clear cell  
- high grade serous  
- endometrioid  

**2.** compare all ovary and endometrium, regardless of cancer type  
**3.** Origin of cancer: clear cell and endometrioid come from endometrium. High grade serous comes from fallopian tubes. We can group clear cell and endometrioid together, then compare them to HGS.  
**4.** Clear cell and endometrioid of ovary both come from endometriosis, it might be interesting to see if there is anything in common between them.  
**5.** Run a separate clustering analysis for all cancer types. Cancers can form distinct clusters, it might be interesting to compare the clusters.  
**6.** Some of these samples are interesting on their own! This folder is dedicated for analyses done on single samples. As of March25th, we have only one sample here: DH8. It formed two clusters on the TSNE plot. We ran DGE anlaysis to udnerstand the differences between these two clusters. 

The files are saved into folders according to the analysis they do. The analyses described above are saved into these folders, respectively:  
**1.** cancer_type  
**2.** tissue_type  
**3.** origin  
**4.** endometriosis  
**5.** clustering   
**6.** individual samples 

Not all of the files above exist at the moment, they will be added later on as well. The folders described above both have the RMarkdown scripts and the knitted html documents.  

#### Troubleshooting - what to do if you having trouble running these scripts
- In the YAML header, make sure you write the small id number first, for example DH10-DH3 won't run, you need to write DH3-DH10. This is how we save data, and this is also true for the other scripts, too.  
- If you move any of the files elsewhere, the script may break since we source many files and data from various locations.  
- The analysis here isn't incorporated into Snakemake since it is a one time analysis with some specifics. 







